### ISSUE TITLE
Please update the version

### ISSUE THREAD

**Issue by Garden-Playhouse** [apostrophecms/random-words#29]
Recent changes have occurred where the developers fixed a spelling error on `index.d.ts` for TypeScript users. However, since there has been not new version after this was pushed out when TypeScript developers install the package, they miss out on this change and experienced issues with the TypeScript spelling error. The workaround for this is to add the following in your `package.json`:

`"random-words": "git://github.com/apostrophecms/random-words.git#e05e942f67387e06b2ac676450a6e41ebefab751"`

The hashtag at the end indicates the latest commit ID. 

To the devs, please push out a version so TypeScript developers can get updated with the latest commits.

Thanks.

**Comment by boutell** [comment]
It's not clear what you're asking us (the upstream developers of random-words itself) to do, if anything. Can you clarify? Thanks.

**Comment by SHF-Tim** [comment]
I think he means this:

https://imgur.com/qwGAnOB

**Comment by SHF-Tim** [comment]
Changed 'randomWords' to 'words' seems to fix it

**Comment by Garden-Playhouse** [comment]
Sorry since I was vague, but what I meant was that there was a spelling error in `index.d.ts` for the word _"separator"_, as it was previously spelled as, _"seperator"_ , but fixed in commit 4a02eda33dc266df98163f80c7bcfb85ba1166fb, on July 2, 2022. However, the developer hasn't published a new version after this fix, so when TypeScript developers download the package, they get the version before this commit was made, resulting in the TypeScript error. If the devs were to simply just publish a new version, then it would push out those spelling error changes to the package.

**Comment by boutell** [comment]
Got it. We'll release it this morning.

**Comment by boutell** [comment]
This was published to npm.

**Comment by Garden-Playhouse** [comment]
Thanks!
