### ISSUE TITLE
Unable to use minLength

### ISSUE THREAD

**Issue by nrgbistro** [apostrophecms/random-words#39]
## To Reproduce

Step by step instructions to reproduce the behavior:

> 1. Import random-words in a *.ts file with `import randomWords from "random-words";`
> 2. Attempt to call randomWords with options: `randomWords({ exactly: 1, minLength: 4, maxLength: 8 });`
> 3. See typescript compile error

## Expected behavior
> Function should be allowed to run

## Describe the bug
> Here is the entire error message:

```
No overload matches this call.
  Overload 1 of 3, '(count: number): string[]', gave the following error.
    Argument of type '{ exactly: number; minLength: number; maxLength: number; }' is not assignable to parameter of type 'number'.
  Overload 2 of 3, '(options: WordsOptions): string[]', gave the following error.
    Argument of type '{ exactly: number; minLength: number; maxLength: number; }' is not assignable to parameter of type 'WordsOptions'.
      Object literal may only specify known properties, and 'minLength' does not exist in type 'WordsOptions'.
  Overload 3 of 3, '(options: JoinedWordsOptions): string', gave the following error.
    Argument of type '{ exactly: number; minLength: number; maxLength: number; }' is not assignable to parameter of type 'JoinedWordsOptions'.
      Object literal may only specify known properties, and 'minLength' does not exist in type 'JoinedWordsOptions'.
```

## Details

**Version of Node.js:**
v18.15.0

**Server Operating System:**
Windows 11

**Comment by BoDonkey** [comment]
Hi @nrgbistro - We had a hold-up because we wanted to merge a second PR with breaking changes. Having back-to-back releases with breaking changes tends to be bad form!  😄 That PR has now been merged, and our next publication will be June 6th. Until then you can install from GitHub if you really need the package for development.
Cheers,
Bob

**Comment by nrgbistro** [comment]
Great, thanks for the heads up. Loving the new 2.0.0 version! Are there any plans to increase the number of words in the package from 1952? I'm using it for a wordle clone and am worried that collisions could occur with such a relatively small set of data. I plan to create a check that ensures the word hasn't already been used, but it seems like the number of words could be increased pretty easily to give more word variation.

**Comment by boutell** [comment]
A larger database would be welcome as a PR. One challenge is making sure it's relatively inoffensive and unalarming stuff, as we use it to generate sample content. The human brain is very good at making things offensive on its own, so we like to not start out with relatively harmless words 😆 

There are many word lists out there. We'd need to make sure the list is public domain or compatibly licensed.

**Comment by nrgbistro** [comment]
great, i'll look into it!
